name: "Build and deploy Google Chrome web extension"
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  sign:
    name: "ğŸ”–ğŸ¤– Release Firefox extension"
    runs-on: ubuntu-latest
    steps:
      - name: "ğŸš€ Checkout"
        uses: actions/checkout@v3

      - name: "ğŸ‘· Install dependencies"
        run: npm install

      - name: "ğŸ“¦ Build application"
        run: npm run build:chrome
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "ğŸ’« Publish chrome extension"
        uses: Klemensas/chrome-extension-upload-action@v1.3
        with:
          refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}
          client-id: ${{ secrets.CHROME_CLIENT_ID }}
          client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
          file-name: web-ext-artifacts/ecoindex.fr-chrome.zip
          app-id: ${{ secrets.CHROME_APP_ID }}
          publish: true

      - name: â¬†ï¸ Upload Chrome artifact
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: web-ext-artifacts/ecoindex.fr-chrome.zip
          asset_name: ecoindex.fr-chrome.zip
          tag: ${{ github.ref }}
